### ISSUE TITLE
Region Not Changing Permanently?

### ISSUE THREAD

**Issue by PolarPeridot** [Possum/LumaLocaleSwitcher#12]
Hi! So I'm trying to change the region Yo-Kai Watch 3 Sukiyaki is so that way my DLC will work, but no matter how many times I change it, whenever I refresh LLS, the region goes back to being the system default. I don't know what to do and it's really frustrating. Please help me?

**Comment by Possum** [comment]
Which version of LLS and also what version of Luma?

**Comment by PolarPeridot** [comment]
The latest version of LLS, and I'm not sure how to check which version of Luma.

**Comment by PolarPeridot** [comment]
I updated Luma and it's still not staying changed. It keeps saying System Default, but when I select the region the language changes too. Does that mean it DID change but it isn't showing that it is?

**Comment by PolarPeridot** [comment]
Nevermind, the DLC still won't load. I'm on the latest version of LLS and the latest version of Luma.

**Comment by PolarPeridot** [comment]
What do I do????

**Comment by PolarPeridot** [comment]
I have the "Enable Region/language emu. and ext. .code" enabled and all of the text files are in the locales folder. Please help me figure out why it isn't wanting to work!

**Comment by Possum** [comment]
I confirmed, it's definitely a bug.

If you are on stable Luma (6.6) try the 0.02 release.

**Comment by PolarPeridot** [comment]
OK, I'll try that version and post what happens.

**Comment by PolarPeridot** [comment]
When I try to open it, FBI says "Failed to acquire kernel access"

**Comment by PolarPeridot** [comment]
I'll try opening FBI itself then install it

**Comment by PolarPeridot** [comment]
Hooray, it finally worked!!! Thank you!

**Comment by Possum** [comment]
Reopened because there *is* a bug that needs to be fixed. Thanks for the report!

**Comment by PolarPeridot** [comment]
No problem! :) Glad I was able to help you find the bug.

**Comment by Possum** [comment]
This was a display issue as far as I can tell, and should be fixed in the latest release.
