### ISSUE TITLE
[suggestion] Hide unneeded things like system titles and dlc

### ISSUE THREAD

**Issue by CouldBeWolf** [Possum/LumaLocaleSwitcher#4]
I think system both system titles and dlc should be automatically hidden and maybe made possible to show as an option. Can't believe these would ever be needed for this.

DSi games are probably never needed to be available for this either.

PS: As far as I can tell, only regular 3DS games start with 00040000.
Updates start with 0004000E
DLC start with 0004008C
And the first system titles start with 00040010
DS/DSi related stuff start with 0004800

I'm sure I didn't need to list those, but I did.

**Comment by Possum** [comment]
I like this idea. I will need to change the "config file" format (since it currently is just a line with the directory to look).

**Comment by Possum** [comment]
I will be implementing a subset of this request in a simpler matter, just hiding the "NAND" titles by default and allowing pressing the "Y" button to toggle them on and off. This will hide the system and DS[i] titles.

**Comment by Possum** [comment]
This feature is implemented in the latest release.
