### ISSUE TITLE
Spoof location for game.

### ISSUE THREAD

**Issue by JumperGerald** [Possum/LumaLocaleSwitcher#8]
I am unsure if this issue would be for you or the Luma thread. I would like to spoof location as well as region. IE: When I catch a pokemon after I do a region/lang spoof, The pokemon data will say that I have a JPN 3ds but the location was California. I would like to spoof this.

**Comment by 3096** [comment]
I guess this goes to Luma

**Comment by Possum** [comment]
I think this is a great idea, but I'm closing this ticket because the changes would need to be made at a lower level (i.e., the CFW level). If Luma3DS implemented a similar method to spoof location, I would consider adding a UI for that.

**Comment by 3096** [comment]
Well, TuxSH on Luma's side already denied it claiming "not possible ATM" so I guess region changing is the only way
